# Generated by Django 4.2.16 on 2024-11-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desired_position', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('score', models.IntegerField()),
                ('ai_evaluation', models.CharField(max_length=50)),
            ],
        ),
    ]
